# The gate that makes the contract real. Every target here is also a CI step;
# nothing in CI does something you cannot run locally with one word.

GO      ?= go
BIN     := bin
MODULES := . ./auth ./binding/rest ./driver/mqtt ./driver/nats ./driver/ws ./errors \
           ./examples/catalog ./frontend/dsl ./frontend/openapi ./ix ./tools ./validate

.PHONY: all
all: plugins generate lint test

## plugins: build every protoc plugin into ./bin, which buf invokes by path.
##
## The Go generators are pinned and installed locally rather than pulled from
## the remote plugin registry. Remote plugins are rate limited, and a drift
## gate that fails because a registry was busy is a gate people learn to
## ignore -- so the one command CI depends on most does not touch the network.
.PHONY: plugins
plugins:
	GOBIN=$(CURDIR)/$(BIN) $(GO) install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.12
	GOBIN=$(CURDIR)/$(BIN) $(GO) install connectrpc.com/connect/cmd/protoc-gen-connect-go@v1.20.0
	$(GO) build -o $(BIN)/protoc-gen-bus   ./tools/cmd/protoc-gen-bus
	$(GO) build -o $(BIN)/protoc-gen-cli   ./tools/cmd/protoc-gen-cli
	$(GO) build -o $(BIN)/protoc-gen-authz ./auth/cmd/protoc-gen-authz

## ix: build the CLI.
.PHONY: ix
ix:
	$(GO) build -o $(BIN)/ix ./ix/cmd/ix

## generate: this repo is a framework monorepo -- five proto modules in one buf
## workspace, each generating into its own Go module. That is not the shape
## `ix` is for, and pretending otherwise would mean bending the tool to its own
## repository. So the framework's own protos are generated from buf templates,
## and the example -- which IS the shape ix is for -- is generated by ix.
.PHONY: generate
generate: generate-framework generate-example

.PHONY: generate-framework
generate-framework: plugins
	./hack/bufgen.sh --template buf.gen.core.yaml   api
	./hack/bufgen.sh --template buf.gen.auth.yaml   auth/api
	./hack/bufgen.sh --template buf.gen.errors.yaml errors/api
	./hack/bufgen.sh --template tools/buf.gen.yaml  tools/api
	./hack/bufgen.sh --template buf.gen.catalog.yaml examples/catalog/api

.PHONY: generate-example
generate-example: plugins ix
	cd examples/catalog && ../../$(BIN)/ix generate

.PHONY: fmt
fmt:
	buf format -w
	$(GO) fmt ./...

.PHONY: lint
lint: ix
	buf lint
	cd examples/catalog && ../../$(BIN)/ix lint

.PHONY: breaking
breaking:
	buf breaking --against '.git#branch=main'

## verify: the drift gate. Generated output is COMMITTED; this is what makes
## that true rather than aspirational, and it is the whole reason the contract
## cannot drift. `ix verify` gates the example; the git diff gates everything
## the framework generates for itself.
.PHONY: verify
verify: generate
	cd examples/catalog && ../../$(BIN)/ix verify
	@git diff --exit-code -- '**/gen/**' \
	  || (echo "generated output is stale: run 'make generate'"; exit 1)

## test: every module. A single `go test ./...` only covers the one you are in.
.PHONY: test
test:
	@set -e; for m in $(MODULES); do \
	  echo "== $$m"; (cd $$m && $(GO) test ./...); \
	done

.PHONY: vet
vet:
	@set -e; for m in $(MODULES); do (cd $$m && $(GO) vet ./...); done

## depcheck: the dependency rule, enforced. Core imports no broker client, no
## HTTP router, no policy engine and no auth module.
.PHONY: depcheck
depcheck:
	./hack/depcheck.sh

.PHONY: clean
clean:
	rm -rf $(BIN)
