// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: interchange/validate/testdata/v1/fixture.proto

package testdatav1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The fixture contract. The rules below are written ONCE, here, and the test
// asserts they are enforced identically on the Connect road and on the bus --
// which is the claim the module exists to make.
type CreateProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	RateLimit     int32                  `protobuf:"varint,3,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProviderRequest) Reset() {
	*x = CreateProviderRequest{}
	mi := &file_interchange_validate_testdata_v1_fixture_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProviderRequest) ProtoMessage() {}

func (x *CreateProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_interchange_validate_testdata_v1_fixture_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProviderRequest.ProtoReflect.Descriptor instead.
func (*CreateProviderRequest) Descriptor() ([]byte, []int) {
	return file_interchange_validate_testdata_v1_fixture_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProviderRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProviderRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateProviderRequest) GetRateLimit() int32 {
	if x != nil {
		return x.RateLimit
	}
	return 0
}

type CreateProviderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProviderResponse) Reset() {
	*x = CreateProviderResponse{}
	mi := &file_interchange_validate_testdata_v1_fixture_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProviderResponse) ProtoMessage() {}

func (x *CreateProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_interchange_validate_testdata_v1_fixture_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProviderResponse.ProtoReflect.Descriptor instead.
func (*CreateProviderResponse) Descriptor() ([]byte, []int) {
	return file_interchange_validate_testdata_v1_fixture_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProviderResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_interchange_validate_testdata_v1_fixture_proto protoreflect.FileDescriptor

const file_interchange_validate_testdata_v1_fixture_proto_rawDesc = "" +
	"\n" +
	".interchange/validate/testdata/v1/fixture.proto\x12 interchange.validate.testdata.v1\x1a\x1bbuf/validate/validate.proto\"}\n" +
	"\x15CreateProviderRequest\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x03\x18@R\x04name\x12\x1d\n" +
	"\x05email\x18\x02 \x01(\tB\a\xbaH\x04r\x02`\x01R\x05email\x12&\n" +
	"\n" +
	"rate_limit\x18\x03 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\trateLimit\"(\n" +
	"\x16CreateProviderResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02idB\xbf\x02\n" +
	"$com.interchange.validate.testdata.v1B\fFixtureProtoP\x01Zfgithub.com/darmawan01/interchange/validate/internal/testpb/interchange/validate/testdata/v1;testdatav1\xa2\x02\x03IVT\xaa\x02 Interchange.Validate.Testdata.V1\xca\x02 Interchange\\Validate\\Testdata\\V1\xe2\x02,Interchange\\Validate\\Testdata\\V1\\GPBMetadata\xea\x02#Interchange::Validate::Testdata::V1b\x06proto3"

var (
	file_interchange_validate_testdata_v1_fixture_proto_rawDescOnce sync.Once
	file_interchange_validate_testdata_v1_fixture_proto_rawDescData []byte
)

func file_interchange_validate_testdata_v1_fixture_proto_rawDescGZIP() []byte {
	file_interchange_validate_testdata_v1_fixture_proto_rawDescOnce.Do(func() {
		file_interchange_validate_testdata_v1_fixture_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_interchange_validate_testdata_v1_fixture_proto_rawDesc), len(file_interchange_validate_testdata_v1_fixture_proto_rawDesc)))
	})
	return file_interchange_validate_testdata_v1_fixture_proto_rawDescData
}

var file_interchange_validate_testdata_v1_fixture_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_interchange_validate_testdata_v1_fixture_proto_goTypes = []any{
	(*CreateProviderRequest)(nil),  // 0: interchange.validate.testdata.v1.CreateProviderRequest
	(*CreateProviderResponse)(nil), // 1: interchange.validate.testdata.v1.CreateProviderResponse
}
var file_interchange_validate_testdata_v1_fixture_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_interchange_validate_testdata_v1_fixture_proto_init() }
func file_interchange_validate_testdata_v1_fixture_proto_init() {
	if File_interchange_validate_testdata_v1_fixture_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_interchange_validate_testdata_v1_fixture_proto_rawDesc), len(file_interchange_validate_testdata_v1_fixture_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_interchange_validate_testdata_v1_fixture_proto_goTypes,
		DependencyIndexes: file_interchange_validate_testdata_v1_fixture_proto_depIdxs,
		MessageInfos:      file_interchange_validate_testdata_v1_fixture_proto_msgTypes,
	}.Build()
	File_interchange_validate_testdata_v1_fixture_proto = out.File
	file_interchange_validate_testdata_v1_fixture_proto_goTypes = nil
	file_interchange_validate_testdata_v1_fixture_proto_depIdxs = nil
}
