package openapi

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
)

// The emitted .proto is committed and sits under the drift gate, so this file
// has one hard requirement: the same document must produce the same bytes.
// Everything that could carry map iteration order into the output is sorted
// here, at the point of emission, rather than trusted to arrive sorted.

type protoFile struct {
	Path      string // the proto import path, e.g. payments/v1/payments.proto
	source    string // the document it came from, for a collision diagnostic
	Package   string
	GoPackage string
	Imports   map[string]bool
	Messages  []*protoMessage
	Enums     []*protoEnum
	Service   *protoService
}

type protoMessage struct {
	Name    string
	Comment string
	Fields  []*protoField
	Nested  []*protoMessage
	Enums   []*protoEnum
	// Oneofs are the names of oneof blocks, in declaration order; a field
	// joins one by naming it.
	Oneofs []string
}

type protoField struct {
	Name     string
	Type     string
	Number   int
	Repeated bool
	Optional bool
	Oneof    string
	Comment  string
}

type protoEnum struct {
	Name    string
	Comment string
	Values  []protoEnumValue
}

type protoEnumValue struct {
	Name   string
	Number int
}

type protoService struct {
	Name       string
	Comment    string
	Transports *transportOptions
	Methods    []*protoMethod
}

type protoMethod struct {
	Name       string
	Input      string
	Output     string
	Comment    string
	HTTP       *httpRule
	Idempotent bool
	Transports *transportOptions
	Auth       *authOptions
	CLI        *cliOptions
	Internal   bool
}

type httpRule struct {
	Verb string // get, post, put, patch, delete
	Path string
	Body string // "", "*", or a field name
}

func (f *protoFile) importPath(p string) {
	if f.Imports == nil {
		f.Imports = map[string]bool{}
	}
	f.Imports[p] = true
}

// String renders the file. Top-level declarations are sorted by name and the
// service comes last: a stable order that does not depend on the order the
// converter happened to create them in.
func (f *protoFile) String() string {
	var b strings.Builder
	b.WriteString("// Code generated by the interchange openapi frontend. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Edit the OpenAPI document and re-run `ix import`; this file is the\n")
	b.WriteString("// committed artifact of that import and is checked by the drift gate.\n\n")
	b.WriteString("syntax = \"proto3\";\n\n")
	fmt.Fprintf(&b, "package %s;\n\n", f.Package)

	imports := make([]string, 0, len(f.Imports))
	for p := range f.Imports {
		imports = append(imports, p)
	}
	sort.Strings(imports)
	for _, p := range imports {
		fmt.Fprintf(&b, "import %q;\n", p)
	}
	if len(imports) > 0 {
		b.WriteString("\n")
	}
	if f.GoPackage != "" {
		fmt.Fprintf(&b, "option go_package = %q;\n\n", f.GoPackage)
	}

	enums := append([]*protoEnum(nil), f.Enums...)
	sort.Slice(enums, func(i, j int) bool { return enums[i].Name < enums[j].Name })
	for _, e := range enums {
		e.write(&b, "")
		b.WriteString("\n")
	}

	msgs := append([]*protoMessage(nil), f.Messages...)
	sort.Slice(msgs, func(i, j int) bool { return msgs[i].Name < msgs[j].Name })
	for _, m := range msgs {
		m.write(&b, "")
		b.WriteString("\n")
	}

	if f.Service != nil {
		f.Service.write(&b)
	}
	return b.String()
}

func writeComment(b *strings.Builder, indent, comment string) {
	if comment == "" {
		return
	}
	for _, line := range strings.Split(comment, "\n") {
		if line == "" {
			fmt.Fprintf(b, "%s//\n", indent)
			continue
		}
		fmt.Fprintf(b, "%s// %s\n", indent, line)
	}
}

func (m *protoMessage) write(b *strings.Builder, indent string) {
	writeComment(b, indent, m.Comment)
	fmt.Fprintf(b, "%smessage %s {\n", indent, m.Name)
	inner := indent + "  "

	enums := append([]*protoEnum(nil), m.Enums...)
	sort.Slice(enums, func(i, j int) bool { return enums[i].Name < enums[j].Name })
	for _, e := range enums {
		e.write(b, inner)
		b.WriteString("\n")
	}
	nested := append([]*protoMessage(nil), m.Nested...)
	sort.Slice(nested, func(i, j int) bool { return nested[i].Name < nested[j].Name })
	for _, n := range nested {
		n.write(b, inner)
		b.WriteString("\n")
	}

	fields := append([]*protoField(nil), m.Fields...)
	sort.Slice(fields, func(i, j int) bool { return fields[i].Number < fields[j].Number })

	// Fields outside any oneof keep their number order; each oneof block is
	// emitted once, where its lowest-numbered member falls.
	emitted := map[string]bool{}
	for _, f := range fields {
		if f.Oneof == "" {
			f.write(b, inner)
			continue
		}
		if emitted[f.Oneof] {
			continue
		}
		emitted[f.Oneof] = true
		fmt.Fprintf(b, "%soneof %s {\n", inner, f.Oneof)
		for _, g := range fields {
			if g.Oneof == f.Oneof {
				g.writeIn(b, inner+"  ")
			}
		}
		fmt.Fprintf(b, "%s}\n", inner)
	}
	fmt.Fprintf(b, "%s}\n", indent)
}

func (f *protoField) write(b *strings.Builder, indent string) {
	writeComment(b, indent, f.Comment)
	prefix := ""
	switch {
	case f.Repeated:
		prefix = "repeated "
	case f.Optional:
		prefix = "optional "
	}
	fmt.Fprintf(b, "%s%s%s %s = %d;\n", indent, prefix, f.Type, f.Name, f.Number)
}

// writeIn emits a field inside a oneof, where neither repeated nor optional is
// legal.
func (f *protoField) writeIn(b *strings.Builder, indent string) {
	writeComment(b, indent, f.Comment)
	fmt.Fprintf(b, "%s%s %s = %d;\n", indent, f.Type, f.Name, f.Number)
}

func (e *protoEnum) write(b *strings.Builder, indent string) {
	writeComment(b, indent, e.Comment)
	fmt.Fprintf(b, "%senum %s {\n", indent, e.Name)
	vals := append([]protoEnumValue(nil), e.Values...)
	sort.Slice(vals, func(i, j int) bool { return vals[i].Number < vals[j].Number })
	for _, v := range vals {
		fmt.Fprintf(b, "%s  %s = %d;\n", indent, v.Name, v.Number)
	}
	fmt.Fprintf(b, "%s}\n", indent)
}

func (s *protoService) write(b *strings.Builder) {
	writeComment(b, "", s.Comment)
	fmt.Fprintf(b, "service %s {\n", s.Name)
	if s.Transports != nil {
		fmt.Fprintf(b, "  option (interchange.transport.v1.service_transports) = %s;\n\n",
			s.Transports.render("  "))
	}
	methods := append([]*protoMethod(nil), s.Methods...)
	sort.Slice(methods, func(i, j int) bool { return methods[i].Name < methods[j].Name })
	for i, m := range methods {
		if i > 0 {
			b.WriteString("\n")
		}
		m.write(b)
	}
	b.WriteString("}\n")
}

func (m *protoMethod) write(b *strings.Builder) {
	writeComment(b, "  ", m.Comment)
	fmt.Fprintf(b, "  rpc %s(%s) returns (%s) {\n", m.Name, m.Input, m.Output)
	if m.HTTP != nil {
		fmt.Fprintf(b, "    option (google.api.http) = %s;\n", m.HTTP.render("    "))
	}
	if m.Idempotent {
		b.WriteString("    option idempotency_level = NO_SIDE_EFFECTS;\n")
	}
	if m.Internal {
		b.WriteString("    option (interchange.transport.v1.internal) = true;\n")
	}
	if m.Transports != nil {
		fmt.Fprintf(b, "    option (interchange.transport.v1.transports) = %s;\n", m.Transports.render("    "))
	}
	if m.Auth != nil {
		fmt.Fprintf(b, "    option (interchange.auth.v1.auth) = %s;\n", m.Auth.render("    "))
	}
	if m.CLI != nil {
		fmt.Fprintf(b, "    option (interchange.cli.v1.command) = %s;\n", m.CLI.render("    "))
	}
	b.WriteString("  }\n")
}

func (h *httpRule) render(indent string) string {
	var b strings.Builder
	b.WriteString("{\n")
	fmt.Fprintf(&b, "%s  %s: %q\n", indent, h.Verb, h.Path)
	if h.Body != "" {
		fmt.Fprintf(&b, "%s  body: %q\n", indent, h.Body)
	}
	fmt.Fprintf(&b, "%s}", indent)
	return b.String()
}

func (t *transportOptions) render(indent string) string {
	var b strings.Builder
	b.WriteString("{\n")
	fmt.Fprintf(&b, "%s  on: [%s]\n", indent, strings.Join(t.On, ", "))
	if t.Group != "" {
		fmt.Fprintf(&b, "%s  group: %q\n", indent, t.Group)
	}
	fmt.Fprintf(&b, "%s}", indent)
	return b.String()
}

func (a *authOptions) render(indent string) string {
	var b strings.Builder
	b.WriteString("{\n")
	if len(a.AuthTypes) > 0 {
		fmt.Fprintf(&b, "%s  auth_types: [%s]\n", indent, strings.Join(a.AuthTypes, ", "))
	}
	if a.Permission != nil {
		fmt.Fprintf(&b, "%s  permission: {resource: %q verb: %s}\n", indent, a.Permission.Resource, a.Permission.Verb)
	}
	if a.Public {
		fmt.Fprintf(&b, "%s  public: true\n", indent)
	}
	if a.Platform {
		fmt.Fprintf(&b, "%s  platform: true\n", indent)
	}
	fmt.Fprintf(&b, "%s}", indent)
	return b.String()
}

func (c *cliOptions) render(indent string) string {
	var b strings.Builder
	b.WriteString("{\n")
	if len(c.Path) > 0 {
		fmt.Fprintf(&b, "%s  path: [%s]\n", indent, quoteList(c.Path))
	}
	if len(c.Args) > 0 {
		fmt.Fprintf(&b, "%s  args: [%s]\n", indent, quoteList(c.Args))
	}
	if c.Short != "" {
		fmt.Fprintf(&b, "%s  short: %q\n", indent, c.Short)
	}
	if c.Long != "" {
		fmt.Fprintf(&b, "%s  long: %q\n", indent, c.Long)
	}
	if c.Skip {
		fmt.Fprintf(&b, "%s  skip: true\n", indent)
	}
	fmt.Fprintf(&b, "%s}", indent)
	return b.String()
}

func quoteList(ss []string) string {
	out := make([]string, len(ss))
	for i, s := range ss {
		out[i] = strconv.Quote(s)
	}
	return strings.Join(out, ", ")
}
