// Package openapi is the OpenAPI 3.x frontend: it turns an OpenAPI document
// into canonical protobuf descriptors and the .proto source they were compiled
// from.
//
// The transform is lossy in one direction only. Paths become RPCs, schemas
// become messages, and every construct that has no canonical proto form --
// oneOf, anyOf, a required-and-nullable property, a name that collides --
// stops the import with its exact source location rather than being dropped
// (§09, "total or loud"). The emitted .proto is the artifact: it is committed,
// reviewed, and regenerated by the drift gate, so this package guarantees the
// same document produces the same bytes.
//
// Round-tripping is explicitly not a goal. There is no proto -> OpenAPI path
// here and there will not be one.
package openapi

import (
	"context"
	"fmt"
	"io"
	"log/slog"
	"regexp"
	"sort"
	"strings"

	"github.com/darmawan01/interchange"
	"github.com/pb33f/libopenapi"
	"github.com/pb33f/libopenapi/datamodel"
	"github.com/pb33f/libopenapi/datamodel/high/base"
	"google.golang.org/protobuf/reflect/protoregistry"
	"google.golang.org/protobuf/types/descriptorpb"
)

// Frontend is the OpenAPI 3.x adapter. Use New.
type Frontend struct{}

// New returns the OpenAPI frontend.
func New() interchange.Frontend { return &Frontend{} }

// Register makes the frontend available to the whole toolchain.
func Register() { interchange.RegisterFrontend(New()) }

func init() { Register() }

// Name is the identifier used in interchange.yaml.
func (f *Frontend) Name() string { return "openapi" }

// openapiKey matches a top-level `openapi: 3.x` in YAML or JSON. Detect is
// deliberately narrow: DetectFrontend treats two claimants as an error, so
// claiming a Swagger 2.0 document or an AsyncAPI file would break detection
// for the frontend that should have had it.
var openapiKey = regexp.MustCompile(`(?m)^[\s{]*"?openapi"?\s*:\s*"?3\.\d`)

// Detect reports whether this frontend claims the file.
func (f *Frontend) Detect(path string, head []byte) bool {
	return openapiKey.Find(head) != nil
}

// Parse implements interchange.Frontend.
//
// The frontend has two things to say that this signature has no room for: the
// import report `ix import` renders, and the .proto source that is the
// committed artifact. Import returns both; Parse is the interface-shaped view
// of the same run.
func (f *Frontend) Parse(ctx context.Context, src interchange.Sources, opt interchange.Options) (*descriptorpb.FileDescriptorSet, interchange.Diagnostics, error) {
	res, err := f.Import(ctx, src, opt)
	return res.Files, res.Diagnostics, err
}

// ProtoSources implements interchange.SourceEmitter: the emitted .proto is the
// artifact this frontend exists to produce, and it comes from the same run
// that produced the descriptors, so the committed text and the IR cannot
// describe different contracts.
func (f *Frontend) ProtoSources(ctx context.Context, src interchange.Sources, opt interchange.Options) (map[string][]byte, interchange.Diagnostics, error) {
	res, err := f.Import(ctx, src, opt)
	return res.Proto, res.Diagnostics, err
}

// Result is everything one import run produced.
type Result struct {
	// Files is the canonical descriptor set, nil when the import was refused.
	Files *descriptorpb.FileDescriptorSet

	// Proto is the emitted source, keyed by proto import path. Empty when the
	// import was refused -- a partial contract is never written.
	Proto map[string][]byte

	// Diagnostics is everything the run had to say, in document order.
	Diagnostics interchange.Diagnostics

	// Reports is one entry per source document.
	Reports []Report
}

// Report is the structured import summary, so `ix import` renders counts
// rather than re-deriving them from the descriptors.
type Report struct {
	Source   string // the source file name
	Format   string // e.g. "OpenAPI 3.0.3"
	Paths    int
	RPCs     int
	Schemas  int
	Messages int
	Package  string
	Service  string

	// ProtoFile is the path the emitted .proto would be written to.
	ProtoFile string

	// Unresolved is the subset of diagnostics that need a human decision.
	Unresolved interchange.Diagnostics
}

// Summary renders the `ix import` block (§11) from the structured report.
func (r *Result) Summary() string {
	var b strings.Builder
	unresolved := 0
	for _, rep := range r.Reports {
		fmt.Fprintf(&b, "  detected   %s\n", rep.Format)
		b.WriteString("  frontend   openapi\n\n")
		fmt.Fprintf(&b, "  ✓ %d paths      → %d RPCs\n", rep.Paths, rep.RPCs)
		fmt.Fprintf(&b, "  ✓ %d schemas    → %d messages\n", rep.Schemas, rep.Messages)
		if n := len(rep.Unresolved); n > 0 {
			fmt.Fprintf(&b, "  ⚠ %d %s need%s a decision:\n\n", n, plural(n, "construct"), verbS(n))
			for _, d := range rep.Unresolved {
				fmt.Fprintf(&b, "    %s:%d  %s\n", d.Path, d.Line, d.Message)
				if d.Hint != "" {
					fmt.Fprintf(&b, "                       → %s\n", d.Hint)
				}
			}
			b.WriteString("\n")
		}
		unresolved += len(rep.Unresolved)
	}
	// "nothing written" is a claim about what happened, not about how many
	// items were flagged: under on_missing_auth=warn the import succeeds with
	// items still listed, and saying nothing was written would be a lie of
	// exactly the kind this frontend exists to stop telling.
	if len(r.Proto) > 0 {
		return b.String()
	}
	if unresolved > 0 {
		fmt.Fprintf(&b, "  nothing written — resolve the %d %s above, then re-run\n",
			unresolved, plural(unresolved, "item"))
	} else {
		b.WriteString("  nothing written\n")
	}
	return b.String()
}

func plural(n int, word string) string {
	if n == 1 {
		return word
	}
	return word + "s"
}

func verbS(n int) string {
	if n == 1 {
		return "s"
	}
	return ""
}

// Import runs the frontend and returns the report and the emitted source
// alongside the descriptors.
func (f *Frontend) Import(ctx context.Context, src interchange.Sources, opt interchange.Options) (*Result, error) {
	res := &Result{Proto: map[string][]byte{}}
	var diags interchange.Diagnostics

	deps, err := depRegistry(opt)
	if err != nil {
		return res, err
	}

	sc, scDiags := parseSidecar(sidecarName(src), src.Sidecar)
	diags = append(diags, scDiags...)

	files := map[string]*protoFile{}
	for _, path := range src.Paths {
		content, ok := src.Content[path]
		if !ok {
			diags = append(diags, interchange.Diagnostic{
				Severity: interchange.SeverityError, Path: path,
				Message: "no content for source", Hint: "Sources.Content must carry every path",
			})
			continue
		}
		file, rep, d := f.one(path, content, sc, deps, opt)
		diags = append(diags, d...)
		res.Reports = append(res.Reports, rep)
		if file == nil {
			continue
		}
		if prev, dup := files[file.Path]; dup {
			diags = append(diags, interchange.Diagnostic{
				Severity: interchange.SeverityError, Path: path,
				Message: fmt.Sprintf("%s is also the file %s emits", file.Path, prev.source),
				Hint:    "give one document a different x-interchange-service, or import them separately",
			})
			continue
		}
		files[file.Path] = file
	}
	diags = append(diags, sc.unused()...)

	// Attribute the diagnostics that need a decision back to their source.
	for i := range res.Reports {
		for _, d := range diags {
			if d.Severity != interchange.SeverityNote && (d.Path == res.Reports[i].Source || d.Path == sc.file) {
				res.Reports[i].Unresolved = append(res.Reports[i].Unresolved, d)
			}
		}
	}

	res.Diagnostics = diags
	if err := diags.Err(); err != nil {
		return res, err
	}

	src2 := map[string][]byte{}
	for path, file := range files {
		src2[path] = []byte(file.String())
	}
	fds, err := compile(ctx, src2, deps)
	if err != nil {
		return res, err
	}
	res.Files = fds
	res.Proto = src2
	return res, nil
}

// one converts a single document.
func (f *Frontend) one(path string, content []byte, sc *sidecar, deps *protoregistry.Files, opt interchange.Options) (*protoFile, Report, interchange.Diagnostics) {
	rep := Report{Source: path, Format: "OpenAPI"}

	s, err := newSource(path, content)
	if err != nil {
		return nil, rep, interchange.Diagnostics{{
			Severity: interchange.SeverityError, Path: path,
			Message: "document is not valid YAML or JSON: " + err.Error(),
		}}
	}
	version, _ := s.scalar("/openapi")
	if !strings.HasPrefix(version, "3.") {
		return nil, rep, interchange.Diagnostics{s.at(interchange.SeverityError, "/openapi",
			fmt.Sprintf("%q is not a 3.x document", version),
			"this frontend reads OpenAPI 3.0 and 3.1; convert a 2.0 document first")}
	}
	rep.Format = "OpenAPI " + version

	// $refs are validated before the model is built. libopenapi drops the
	// object that held an unresolvable reference and carries on, which would
	// leave a partial contract; and its own error text names a location only
	// in prose.
	if d := validateRefs(s); len(d) > 0 {
		return nil, rep, d
	}

	doc, err := libopenapi.NewDocumentWithConfiguration(content, &datamodel.DocumentConfiguration{
		AllowFileReferences:   false,
		AllowRemoteReferences: false,
		Logger:                slog.New(slog.NewTextHandler(io.Discard, nil)),
	})
	if err != nil {
		return nil, rep, interchange.Diagnostics{{
			Severity: interchange.SeverityError, Path: path,
			Message: "document could not be read: " + err.Error(),
		}}
	}
	// A build error leaves a partial model -- the object that failed is simply
	// absent -- so the model is never touched after one.
	model, buildErr := doc.BuildV3Model()
	if buildErr != nil || model == nil {
		msgs := []string{"document could not be modelled"}
		if buildErr != nil {
			msgs = strings.Split(buildErr.Error(), "\n")
			sort.Strings(msgs)
		}
		var d interchange.Diagnostics
		for _, m := range msgs {
			if strings.TrimSpace(m) == "" {
				continue
			}
			d = append(d, interchange.Diagnostic{Severity: interchange.SeverityError, Path: path, Message: strings.TrimSpace(m)})
		}
		return nil, rep, d
	}

	c := &converter{src: s, doc: &model.Model, opt: opt, sc: sc, deps: deps}
	c.pkg = firstNonEmpty(rootExtension(s, extPackage), opt.Package)
	if c.pkg == "" {
		return nil, rep, interchange.Diagnostics{{
			Severity: interchange.SeverityError, Path: path,
			Message: "no proto package for this document",
			Hint:    "set Options.Package, or x-interchange-package at the document root",
		}}
	}
	if !validPackage(c.pkg) {
		return nil, rep, interchange.Diagnostics{{
			Severity: interchange.SeverityError, Path: path,
			Message: fmt.Sprintf("%q is not a proto package name", c.pkg),
			Hint:    "dot-separated lower_snake_case, e.g. payments.v1",
		}}
	}
	c.service = serviceName(s, model.Model.Info, opt)
	if !protoIdent(c.service) {
		return nil, rep, interchange.Diagnostics{{
			Severity: interchange.SeverityError, Path: path,
			Message: fmt.Sprintf("%q is not a proto service name", c.service),
			Hint:    "set x-interchange-service at the document root",
		}}
	}

	c.convert()

	rep.Paths, rep.RPCs, rep.Schemas, rep.Messages = c.nPaths, c.nRPCs, c.nSchemas, c.nMessages
	rep.Package, rep.Service, rep.ProtoFile = c.pkg, c.service, c.file.Path
	return c.file, rep, c.diags
}

// validateRefs refuses an external reference and a dangling internal one.
// External references are out of scope by construction: Sources carries the
// bytes a frontend is allowed to see, and reading the filesystem behind its
// back would break `ix` driving an import from a git object or an archive.
func validateRefs(s *source) interchange.Diagnostics {
	var out interchange.Diagnostics
	for _, r := range s.refs() {
		switch {
		case strings.HasPrefix(r.target, "#/"):
			if !s.resolves(r.target) {
				out = append(out, s.at(interchange.SeverityError, r.pointer,
					fmt.Sprintf("$ref %s does not resolve", r.target),
					"check the component name, or add the schema"))
			}
		default:
			out = append(out, s.at(interchange.SeverityError, r.pointer,
				fmt.Sprintf("$ref %s is external", r.target),
				"bundle the document into one file; a frontend never reads the filesystem"))
		}
	}
	return out
}

func rootExtension(s *source, key string) string {
	v, _ := s.scalar("/" + key)
	return v
}

// serviceName resolves the proto service name: the document says it, or the
// caller does, or it is derived from info.title.
func serviceName(s *source, info *base.Info, opt interchange.Options) string {
	if v := rootExtension(s, extService); v != "" {
		return camel(v)
	}
	if v := opt.Params["service"]; v != "" {
		return camel(v)
	}
	title := ""
	if info != nil {
		title = info.Title
	}
	n := camel(title)
	n = strings.TrimSuffix(n, "API")
	n = strings.TrimSuffix(n, "Api")
	if n == "" {
		return ""
	}
	if !strings.HasSuffix(n, "Service") {
		n += "Service"
	}
	return n
}

var packageRe = regexp.MustCompile(`^[a-z][a-z0-9_]*(\.[a-z0-9_]+)*$`)

func validPackage(p string) bool { return packageRe.MatchString(p) }

// sidecarName is the name diagnostics about the sidecar carry.
func sidecarName(src interchange.Sources) string {
	if len(src.Sidecar) == 0 {
		return ""
	}
	if src.SidecarPath != "" {
		return src.SidecarPath
	}
	return "sidecar"
}
