package dsl

import (
	"fmt"
	"sort"
	"strconv"
	"strings"

	interchange "github.com/darmawan01/interchange"
	"gopkg.in/yaml.v3"
)

// The proto files an annotation implies. They are constants rather than
// derived because the extension numbers behind them are fixed by
// docs/annotation-band.md and never move.
const (
	importHTTP       = "google/api/annotations.proto"
	importTransports = "interchange/transport/v1/transports.proto"
	importAuth       = "interchange/auth/v1/auth.proto"
	importCLI        = "interchange/cli/v1/cli.proto"
)

func warning(path string, n *yaml.Node, msg, hint string) interchange.Diagnostic {
	d := interchange.Diagnostic{
		Severity: interchange.SeverityWarning,
		Path:     path,
		Message:  msg,
		Hint:     hint,
	}
	if n != nil {
		d.Line, d.Col = n.Line, n.Column
	}
	return d
}

// render writes the .proto source. This is the artifact: it is what `ix
// import` commits and what a reviewer reads, so it is formatted the way a
// human would write it -- and byte-identical for identical input, because it
// sits under the drift gate.
//
// Ordering: messages, enums, services and RPCs keep declaration order, which
// is the author's narrative and is deterministic; fields and enum values are
// emitted in numeric order, so reordering the YAML can never move a line.
func render(f *file, r *resolver) []byte {
	var b strings.Builder

	fmt.Fprintf(&b, "// Generated by the interchange DSL frontend from %s. DO NOT EDIT.\n", f.path)
	b.WriteString("//\n// Edit the DSL source and re-run `ix generate`.\n\n")
	b.WriteString("syntax = \"proto3\";\n\n")
	fmt.Fprintf(&b, "package %s;\n", f.pkg)

	if imps := r.sortedImports(); len(imps) > 0 {
		b.WriteString("\n")
		for _, p := range imps {
			fmt.Fprintf(&b, "import %s;\n", strconv.Quote(p))
		}
	}
	if f.goPackage != "" {
		fmt.Fprintf(&b, "\noption go_package = %s;\n", strconv.Quote(f.goPackage))
	}

	for _, e := range f.enums {
		b.WriteString("\n")
		renderEnum(&b, e, "")
	}
	for _, m := range f.messages {
		b.WriteString("\n")
		renderMessage(&b, m, "")
	}
	for _, s := range f.services {
		b.WriteString("\n")
		renderService(&b, s)
	}
	return []byte(b.String())
}

func renderDoc(b *strings.Builder, doc, indent string) {
	if doc == "" {
		return
	}
	for _, l := range strings.Split(doc, "\n") {
		if l == "" {
			fmt.Fprintf(b, "%s//\n", indent)
			continue
		}
		fmt.Fprintf(b, "%s// %s\n", indent, l)
	}
}

func renderMessage(b *strings.Builder, m *message, indent string) {
	renderDoc(b, m.doc, indent)
	fmt.Fprintf(b, "%smessage %s {\n", indent, m.name)

	fields := append([]*field{}, m.fields...)
	sort.SliceStable(fields, func(i, j int) bool { return fields[i].num < fields[j].num })
	for i, f := range fields {
		if f.doc != "" && i > 0 {
			b.WriteString("\n")
		}
		renderDoc(b, f.doc, indent+"  ")
		label := ""
		switch {
		case f.repeated:
			label = "repeated "
		case f.optional:
			label = "optional "
		}
		fmt.Fprintf(b, "%s  %s%s %s = %d;\n", indent, label, f.rendered, f.name, f.num)
	}
	for _, e := range m.enums {
		b.WriteString("\n")
		renderEnum(b, e, indent+"  ")
	}
	for _, n := range m.messages {
		b.WriteString("\n")
		renderMessage(b, n, indent+"  ")
	}
	fmt.Fprintf(b, "%s}\n", indent)
}

func renderEnum(b *strings.Builder, e *enum, indent string) {
	renderDoc(b, e.doc, indent)
	fmt.Fprintf(b, "%senum %s {\n", indent, e.name)
	vals := append([]*enumValue{}, e.values...)
	sort.SliceStable(vals, func(i, j int) bool { return vals[i].num < vals[j].num })
	for _, v := range vals {
		fmt.Fprintf(b, "%s  %s = %d;\n", indent, v.name, v.num)
	}
	fmt.Fprintf(b, "%s}\n", indent)
}

func renderService(b *strings.Builder, s *service) {
	renderDoc(b, s.doc, "")
	fmt.Fprintf(b, "service %s {\n", s.name)

	wrote := false
	if s.annot != nil && len(s.annot.transports) > 0 {
		fields := []literalField{{name: "on", value: transportList(s.annot.transports)}}
		if s.annot.group != "" {
			fields = append(fields, literalField{name: "group", value: strconv.Quote(s.annot.group)})
		}
		fmt.Fprintf(b, "  option (interchange.transport.v1.service_transports) = %s;\n",
			literal(fields, "  "))
		wrote = true
	}
	for i, m := range s.rpcs {
		if wrote || i > 0 {
			b.WriteString("\n")
		}
		renderRPC(b, m)
	}
	b.WriteString("}\n")
}

func renderRPC(b *strings.Builder, m *rpc) {
	renderDoc(b, m.doc, "  ")
	head := fmt.Sprintf("  rpc %s(%s) returns (%s)", m.name, m.request, m.response)

	opts := rpcOptions(m.annot)
	if len(opts) == 0 {
		fmt.Fprintf(b, "%s {}\n", head)
		return
	}
	fmt.Fprintf(b, "%s {\n", head)
	for _, o := range opts {
		fmt.Fprintf(b, "    %s\n", o)
	}
	b.WriteString("  }\n")
}

// rpcOptions emits the annotations in a fixed order -- route, idempotency,
// roads, visibility, authorization, CLI -- so the same DSL always produces
// the same bytes.
func rpcOptions(a *annotations) []string {
	if a == nil {
		return nil
	}
	var out []string

	if a.http != nil {
		fields := []literalField{{name: a.http.method, value: strconv.Quote(a.http.path)}}
		if a.http.body != "" {
			fields = append(fields, literalField{name: "body", value: strconv.Quote(a.http.body)})
		}
		out = append(out, "option (google.api.http) = "+literal(fields, "    ")+";")
	}
	switch a.idempotency {
	case "no_side_effects":
		out = append(out, "option idempotency_level = NO_SIDE_EFFECTS;")
	case "idempotent":
		out = append(out, "option idempotency_level = IDEMPOTENT;")
	case "unknown":
		out = append(out, "option idempotency_level = IDEMPOTENCY_UNKNOWN;")
	}
	if len(a.transports) > 0 {
		fields := []literalField{{name: "on", value: transportList(a.transports)}}
		if a.group != "" {
			fields = append(fields, literalField{name: "group", value: strconv.Quote(a.group)})
		}
		out = append(out, "option (interchange.transport.v1.transports) = "+literal(fields, "    ")+";")
	}
	if a.internal {
		out = append(out, "option (interchange.transport.v1.internal) = true;")
	}
	if a.auth != nil {
		var fields []literalField
		if len(a.auth.authTypes) > 0 {
			fields = append(fields, literalField{name: "auth_types", value: prefixedList(a.auth.authTypes, "AUTH_TYPE_")})
		}
		if a.auth.hasPerm {
			fields = append(fields, literalField{
				name:  "permission",
				value: fmt.Sprintf("{resource: %s verb: VERB_%s}", strconv.Quote(a.auth.resource), a.auth.verb),
			})
		}
		if a.auth.public {
			fields = append(fields, literalField{name: "public", value: "true"})
		}
		if a.auth.platform {
			fields = append(fields, literalField{name: "platform", value: "true"})
		}
		out = append(out, "option (interchange.auth.v1.auth) = "+literal(fields, "    ")+";")
	}
	if a.cli != nil {
		var fields []literalField
		if len(a.cli.path) > 0 {
			fields = append(fields, literalField{name: "path", value: quotedList(a.cli.path)})
		}
		if len(a.cli.args) > 0 {
			fields = append(fields, literalField{name: "args", value: quotedList(a.cli.args)})
		}
		if a.cli.short != "" {
			fields = append(fields, literalField{name: "short", value: strconv.Quote(a.cli.short)})
		}
		if a.cli.long != "" {
			fields = append(fields, literalField{name: "long", value: strconv.Quote(a.cli.long)})
		}
		if a.cli.skip {
			fields = append(fields, literalField{name: "skip", value: "true"})
		}
		out = append(out, "option (interchange.cli.v1.command) = "+literal(fields, "    ")+";")
	}
	return out
}

type literalField struct{ name, value string }

// literal renders a message option value: one line when it has a single
// field, one field per line when it has more. Same rule everywhere, so the
// output never depends on how long a path happened to be.
func literal(fields []literalField, indent string) string {
	if len(fields) == 0 {
		return "{}"
	}
	if len(fields) == 1 {
		return "{" + fields[0].name + ": " + fields[0].value + "}"
	}
	var b strings.Builder
	b.WriteString("{\n")
	for _, f := range fields {
		fmt.Fprintf(&b, "%s  %s: %s\n", indent, f.name, f.value)
	}
	b.WriteString(indent + "}")
	return b.String()
}

func transportList(names []string) string { return prefixedList(names, "TRANSPORT_") }

func prefixedList(names []string, prefix string) string {
	out := make([]string, len(names))
	for i, n := range names {
		out[i] = prefix + n
	}
	return "[" + strings.Join(out, ", ") + "]"
}

func quotedList(vals []string) string {
	out := make([]string, len(vals))
	for i, v := range vals {
		out[i] = strconv.Quote(v)
	}
	return "[" + strings.Join(out, ", ") + "]"
}
