package main

import (
	"fmt"
	"path"
	"slices"
	"strings"

	"github.com/darmawan01/interchange"
	transportv1 "github.com/darmawan01/interchange/gen/go/interchange/transport/v1"
	"github.com/darmawan01/interchange/tools/internal/genutil"
	"google.golang.org/protobuf/compiler/protogen"
)

const (
	corePkg      = protogen.GoImportPath("github.com/darmawan01/interchange")
	enginePkg    = protogen.GoImportPath("github.com/darmawan01/interchange/engine")
	transportPkg = protogen.GoImportPath("github.com/darmawan01/interchange/gen/go/interchange/transport/v1")
	protoPkg     = protogen.GoImportPath("google.golang.org/protobuf/proto")
	contextPkg   = protogen.GoImportPath("context")
	timePkg      = protogen.GoImportPath("time")
)

type service struct {
	name     string // bare proto name, "CatalogService"
	goName   string
	fullName string // "catalog.v1.CatalogService"
	methods  []method
}

type method struct {
	name       string
	goName     string
	procedure  string
	comment    string
	input      protogen.GoIdent
	output     protogen.GoIdent
	transports []transportv1.Transport
	group      string
	idempotent bool
	internal   bool
	bus        bool
}

func (s service) hasBus() bool {
	return slices.ContainsFunc(s.methods, func(m method) bool { return m.bus })
}

func generate(p *protogen.Plugin) error {
	files := make([]*protogen.File, 0, len(p.Files))
	for _, f := range p.Files {
		// p.Files carries every transitive import; without this guard the
		// plugin emits a bus client for google/protobuf/descriptor.proto.
		if f.Generate {
			files = append(files, f)
		}
	}
	slices.SortFunc(files, func(a, b *protogen.File) int {
		return strings.Compare(a.Desc.Path(), b.Desc.Path())
	})
	for _, f := range files {
		if len(f.Services) == 0 {
			continue
		}
		svcs, err := model(f)
		if err != nil {
			return err
		}
		emit(p, f, svcs)
	}
	return nil
}

// model reads the annotations off one file and validates them. It runs to
// completion before a byte is emitted: a plugin that writes a partial file
// and then fails leaves a tree that compiles but does not mean what the
// contract says.
func model(f *protogen.File) ([]service, error) {
	svcs := make([]service, 0, len(f.Services))
	for _, s := range f.Services {
		svcOpt := serviceTransportOptions(interchange.ServiceOptions(s.Desc))
		out := service{
			name:     string(s.Desc.Name()),
			goName:   s.GoName,
			fullName: string(s.Desc.FullName()),
		}
		for _, m := range s.Methods {
			if m.Desc.IsStreamingClient() || m.Desc.IsStreamingServer() {
				return nil, fmt.Errorf("%s: %s is a streaming RPC; interchange is unary only, and a binding that quietly dropped it would be a contract the code does not keep",
					genutil.SourceLoc(f, m.Location), m.Desc.FullName())
			}
			opts := interchange.MethodOptions(m.Desc)
			on, group, err := resolve(svcOpt, methodTransportOptions(opts))
			if err != nil {
				return nil, fmt.Errorf("%s: %s: %w", genutil.SourceLoc(f, m.Location), m.Desc.FullName(), err)
			}
			out.methods = append(out.methods, method{
				name:       string(m.Desc.Name()),
				goName:     m.GoName,
				procedure:  "/" + out.fullName + "/" + string(m.Desc.Name()),
				comment:    strings.TrimRight(m.Comments.Leading.String(), "\n"),
				input:      m.Input.GoIdent,
				output:     m.Output.GoIdent,
				transports: on,
				group:      group,
				idempotent: idempotent(opts),
				internal:   methodInternal(opts),
				bus:        onBus(on),
			})
		}
		slices.SortFunc(out.methods, func(a, b method) int { return strings.Compare(a.name, b.name) })
		svcs = append(svcs, out)
	}
	slices.SortFunc(svcs, func(a, b service) int { return strings.Compare(a.name, b.name) })
	return svcs, nil
}

func emit(p *protogen.Plugin, f *protogen.File, svcs []service) {
	pkg := string(f.GoPackageName) + "bus"
	dir := path.Dir(f.GeneratedFilenamePrefix)
	name := path.Join(dir, pkg, path.Base(f.GeneratedFilenamePrefix)+"_bus.pb.go")
	importPath := protogen.GoImportPath(path.Join(string(f.GoImportPath), pkg))

	im := genutil.NewImporter(p)
	var b strings.Builder
	for _, s := range svcs {
		emitService(&b, im, f, s)
	}

	g := p.NewGeneratedFile(name, importPath)
	g.P("// Code generated by protoc-gen-bus. DO NOT EDIT.")
	g.P("// source: ", f.Desc.Path())
	g.P()
	g.P("package ", pkg)
	g.P()
	im.Write(g)
	g.P(b.String())
}

func emitService(b *strings.Builder, im *genutil.Importer, f *protogen.File, s service) {
	pf := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }

	descVar := lowerFirst(s.goName) + "Descriptor"
	pf("// %sName is the fully-qualified proto service name: the name the authz", s.goName)
	pf("// check, the metrics label and the trace span all use, on every road.")
	pf("const %sName = %q", s.goName, s.fullName)
	pf("")
	pf("// Procedures on %s.", s.name)
	pf("const (")
	for _, m := range s.methods {
		pf("\t%s%sProcedure = %q", s.goName, m.goName, m.procedure)
	}
	pf(")")
	pf("")
	pf("// %s is looked up by name rather than by index: inserting an", descVar)
	pf("// RPC in the .proto must not silently repoint the descriptor an optional")
	pf("// module reads its own annotation off at runtime.")
	pf("var %s = %s.Services().ByName(%q)", descVar, im.Ref(f.GoDescriptorIdent), s.name)
	pf("")

	pf("// %sHandler is the server interface. One implementation serves", s.goName)
	pf("// every road: the ServiceDesc below is what both the Connect binding and")
	pf("// the message engine dispatch into.")
	pf("type %sHandler interface {", s.goName)
	for i, m := range s.methods {
		if m.comment != "" {
			if i > 0 {
				pf("")
			}
			pf("%s", indent(m.comment))
		}
		pf("\t%s(%s.Context, *%s) (*%s, error)", m.goName, im.Pkg(contextPkg), im.Ref(m.input), im.Ref(m.output))
	}
	pf("}")
	pf("")

	pf("// New%sDesc returns the descriptor core dispatches through.", s.goName)
	pf("// Registering it once binds every road at once.")
	pf("func New%sDesc() *%s.ServiceDesc {", s.goName, im.Pkg(corePkg))
	pf("\treturn &%s.ServiceDesc{", im.Pkg(corePkg))
	pf("\t\tName: %sName,", s.goName)
	pf("\t\tDesc: %s,", descVar)
	pf("\t\tMethods: []%s.MethodDesc{", im.Pkg(corePkg))
	for _, m := range s.methods {
		emitMethodDesc(b, im, s, m, descVar)
	}
	pf("\t\t},")
	pf("\t}")
	pf("}")
	pf("")

	pf("// Register%s binds impl behind chain. Both *interchange.Registry and", s.goName)
	pf("// a binding satisfy Registrar, so this wiring does not know which road it")
	pf("// was handed.")
	pf("func Register%s(r %s.Registrar, impl %sHandler, chain *%s.ChainSpec) error {",
		s.goName, im.Pkg(corePkg), s.goName, im.Pkg(corePkg))
	pf("\treturn r.Register(New%sDesc(), impl, chain)", s.goName)
	pf("}")
	pf("")

	if s.hasBus() {
		emitBusClient(b, im, s)
	}
}

func emitMethodDesc(b *strings.Builder, im *genutil.Importer, s service, m method, descVar string) {
	pf := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	pf("\t\t\t{")
	pf("\t\t\t\tName:        %q,", m.name)
	pf("\t\t\t\tService:     %sName,", s.goName)
	pf("\t\t\t\tProcedure:   %s%sProcedure,", s.goName, m.goName)
	pf("\t\t\t\tNewRequest:  func() %s.Message { return &%s{} },", im.Pkg(protoPkg), im.Ref(m.input))
	pf("\t\t\t\tNewResponse: func() %s.Message { return &%s{} },", im.Pkg(protoPkg), im.Ref(m.output))
	pf("\t\t\t\tTransports:  []%s.Transport{%s},", im.Pkg(transportPkg), transportList(im, m.transports))
	if m.group != "" {
		pf("\t\t\t\tGroup:       %q,", m.group)
	}
	if m.idempotent {
		pf("\t\t\t\tIdempotent:  true,")
	}
	if m.internal {
		pf("\t\t\t\tInternal:    true,")
	}
	pf("\t\t\t\tDesc:        %s.Methods().ByName(%q),", descVar, m.name)
	pf("\t\t\t\tHandler: func(ctx %s.Context, impl any, req %s.Message) (%s.Message, error) {",
		im.Pkg(contextPkg), im.Pkg(protoPkg), im.Pkg(protoPkg))
	pf("\t\t\t\t\treturn impl.(%sHandler).%s(ctx, req.(*%s))", s.goName, m.goName, im.Ref(m.input))
	pf("\t\t\t\t},")
	pf("\t\t\t},")
}

// emitBusClient writes the calling half. Only methods that actually travel a
// broker get a client method: a generated call to a procedure nothing
// subscribes to is a timeout with a confident-looking signature.
func emitBusClient(b *strings.Builder, im *genutil.Importer, s service) {
	pf := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	client := s.goName + "BusClient"

	pf("// %s calls %s over the message engine.", client, s.name)
	pf("//")
	pf("// A plain method blocks until the reply arrives or the context is done, and")
	pf("// that is the trap: the signature looks local and the call is not. So every")
	pf("// method also has a Within form that takes the deadline as an argument,")
	pf("// and With%sTimeout sets a default for the plain form. Pick one", s.goName)
	pf("// deliberately: the engine's own client timeout is the last line of")
	pf("// defence, not the first.")
	pf("type %s struct {", client)
	pf("\tclient  *%s.Client", im.Pkg(enginePkg))
	pf("\ttimeout %s.Duration", im.Pkg(timePkg))
	pf("}")
	pf("")
	pf("// %sOption configures the client. The type is named per service", client)
	pf("// so that two .proto files in one directory cannot collide on it.")
	pf("type %sOption func(*%s)", client, client)
	pf("")
	pf("// With%sTimeout bounds every call made through the plain method", s.goName)
	pf("// form.")
	pf("func With%sTimeout(d %s.Duration) %sOption {", s.goName, im.Pkg(timePkg), client)
	pf("\treturn func(c *%s) { c.timeout = d }", client)
	pf("}")
	pf("")
	pf("// New%s returns a client over an engine client.", client)
	pf("func New%s(c *%s.Client, opts ...%sOption) *%s {", client, im.Pkg(enginePkg), client, client)
	pf("\tout := &%s{client: c}", client)
	pf("\tfor _, o := range opts {")
	pf("\t\to(out)")
	pf("\t}")
	pf("\treturn out")
	pf("}")

	for _, m := range s.methods {
		if !m.bus {
			continue
		}
		in, outT := "*"+im.Ref(m.input), "*"+im.Ref(m.output)
		pf("")
		pf("// %s calls %s and blocks.", m.goName, m.procedure)
		pf("// It uses the client's default timeout if one was configured, and")
		pf("// otherwise waits as long as ctx allows.")
		pf("func (c *%s) %s(ctx %s.Context, req %s) (%s, error) {", client, m.goName, im.Pkg(contextPkg), in, outT)
		pf("\tif c.timeout > 0 {")
		pf("\t\tvar cancel %s.CancelFunc", im.Pkg(contextPkg))
		pf("\t\tctx, cancel = %s.WithTimeout(ctx, c.timeout)", im.Pkg(contextPkg))
		pf("\t\tdefer cancel()")
		pf("\t}")
		pf("\tout := &%s{}", im.Ref(m.output))
		pf("\tif err := c.client.Invoke(ctx, %s%sProcedure, req, out); err != nil {", s.goName, m.goName)
		pf("\t\treturn nil, err")
		pf("\t}")
		pf("\treturn out, nil")
		pf("}")
		pf("")
		pf("// %sWithin is %s with the network deadline in the signature,", m.goName, m.goName)
		pf("// where a caller cannot miss it.")
		pf("func (c *%s) %sWithin(ctx %s.Context, timeout %s.Duration, req %s) (%s, error) {",
			client, m.goName, im.Pkg(contextPkg), im.Pkg(timePkg), in, outT)
		pf("\tctx, cancel := %s.WithTimeout(ctx, timeout)", im.Pkg(contextPkg))
		pf("\tdefer cancel()")
		pf("\tout := &%s{}", im.Ref(m.output))
		pf("\tif err := c.client.Invoke(ctx, %s%sProcedure, req, out); err != nil {", s.goName, m.goName)
		pf("\t\treturn nil, err")
		pf("\t}")
		pf("\treturn out, nil")
		pf("}")
	}
	pf("")
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

// indent re-indents a doc comment for use inside an interface body.
func indent(comment string) string {
	lines := strings.Split(comment, "\n")
	for i, l := range lines {
		lines[i] = "\t" + strings.TrimSpace(l)
	}
	return strings.Join(lines, "\n")
}

// transportList renders the resolved roads as a Go composite literal body.
func transportList(im *genutil.Importer, on []transportv1.Transport) string {
	pkg := im.Pkg(transportPkg)
	parts := make([]string, 0, len(on))
	for _, t := range on {
		parts = append(parts, pkg+".Transport_"+t.String())
	}
	return strings.Join(parts, ", ")
}
