package main

import (
	"slices"
	"strings"
	"testing"

	transportv1 "github.com/darmawan01/interchange/gen/go/interchange/transport/v1"
	"github.com/darmawan01/interchange/tools/internal/plugintest"
	fixturev1 "github.com/darmawan01/interchange/tools/testdata/gen/interchange/fixture/v1"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"
)

func fixtureRequest(t *testing.T) *pluginpb.CodeGeneratorRequest {
	t.Helper()
	return plugintest.Request(t, "paths=source_relative",
		fixturev1.File_interchange_fixture_v1_extra_proto,
		fixturev1.File_interchange_fixture_v1_fixture_proto)
}

func run(t *testing.T) map[string]string {
	t.Helper()
	files, err := plugintest.Run(fixtureRequest(t), protogen.Options{}, generate)
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	return files
}

// TestGolden is the drift gate in miniature: the goldens are the committed
// package under testdata/gen, so `go build ./...` compiles the generator's
// own output against core.
func TestGolden(t *testing.T) {
	plugintest.Golden(t, "../../testdata/gen", run(t))
}

// TestOnlyFilesToGenerate is the `file.Generate` guard: cli.proto,
// transports.proto and descriptor.proto are all in the request.
func TestOnlyFilesToGenerate(t *testing.T) {
	var names []string
	for n := range run(t) {
		names = append(names, n)
	}
	slices.Sort(names)
	want := []string{
		"interchange/fixture/v1/fixturev1bus/extra_bus.pb.go",
		"interchange/fixture/v1/fixturev1bus/fixture_bus.pb.go",
	}
	if !slices.Equal(names, want) {
		t.Errorf("emitted %v, want %v", names, want)
	}
}

func TestDeterministic(t *testing.T) {
	first, second := run(t), run(t)
	if len(first) != len(second) {
		t.Fatalf("run one emitted %d files, run two emitted %d", len(first), len(second))
	}
	for name, a := range first {
		if b := second[name]; a != b {
			t.Errorf("%s differs between runs", name)
		}
	}
}

// TestResolvedTransports pins the three cases the annotation has, read off
// the generated bytes rather than off an internal structure.
func TestResolvedTransports(t *testing.T) {
	src := run(t)["interchange/fixture/v1/fixturev1bus/fixture_bus.pb.go"]
	for _, tc := range []struct {
		method string
		want   string
	}{
		// Inherits the service-level default and its group.
		{"GetItem", "transportv1.Transport_TRANSPORT_RPC, transportv1.Transport_TRANSPORT_BUS"},
		// Replaces it entirely -- sorted by enum value, not by the order
		// they were typed in the .proto.
		{"PublishItem", "transportv1.Transport_TRANSPORT_BUS, transportv1.Transport_TRANSPORT_MQTT"},
	} {
		block := methodBlock(t, src, tc.method)
		if !strings.Contains(block, "Transports:  []transportv1.Transport{"+tc.want+"}") {
			t.Errorf("%s: want transports %s, got:\n%s", tc.method, tc.want, block)
		}
	}
	if b := methodBlock(t, src, "PublishItem"); !strings.Contains(b, `Group:       "publishers"`) {
		t.Errorf("PublishItem: per-method group did not replace the service group:\n%s", b)
	}
	if b := methodBlock(t, src, "GetItem"); !strings.Contains(b, `Group:       "fixtures"`) {
		t.Errorf("GetItem: did not inherit the service group:\n%s", b)
	}
	if b := methodBlock(t, src, "GetItem"); !strings.Contains(b, "Idempotent:  true") {
		t.Errorf("GetItem: NO_SIDE_EFFECTS did not reach MethodDesc:\n%s", b)
	}
	if b := methodBlock(t, src, "Reindex"); !strings.Contains(b, "Internal:    true") {
		t.Errorf("Reindex: (internal) did not reach MethodDesc:\n%s", b)
	}

	// PlainService carries no annotation anywhere: the two synchronous roads.
	if b := methodBlock(t, src, "Ping"); !strings.Contains(b,
		"Transports:  []transportv1.Transport{transportv1.Transport_TRANSPORT_RPC, transportv1.Transport_TRANSPORT_REST}") {
		t.Errorf("Ping: want the default roads:\n%s", b)
	}
}

func methodBlock(t *testing.T, src, method string) string {
	t.Helper()
	start := strings.Index(src, "Name:        \""+method+"\",")
	if start < 0 {
		t.Fatalf("no MethodDesc for %s in generated source", method)
	}
	end := strings.Index(src[start:], "\n\t\t\t},")
	if end < 0 {
		t.Fatalf("unterminated MethodDesc for %s", method)
	}
	return src[start : start+end]
}

func TestResolve(t *testing.T) {
	svc := &transportv1.ServiceTransportOptions{
		On:    []transportv1.Transport{transportv1.Transport_TRANSPORT_BUS},
		Group: "svc",
	}
	for _, tc := range []struct {
		name      string
		svc       *transportv1.ServiceTransportOptions
		method    *transportv1.TransportOptions
		want      []transportv1.Transport
		wantGroup string
		wantErr   string
	}{
		{
			name: "neither annotation",
			want: defaultRoads,
		},
		{
			name:      "service default",
			svc:       svc,
			want:      []transportv1.Transport{transportv1.Transport_TRANSPORT_BUS},
			wantGroup: "svc",
		},
		{
			name:      "method replaces service entirely",
			svc:       svc,
			method:    &transportv1.TransportOptions{On: []transportv1.Transport{transportv1.Transport_TRANSPORT_REST}},
			want:      []transportv1.Transport{transportv1.Transport_TRANSPORT_REST},
			wantGroup: "", // replacement, not merge: the service group is gone too.
		},
		{
			name:   "sorted and deduped",
			method: &transportv1.TransportOptions{On: []transportv1.Transport{transportv1.Transport_TRANSPORT_WS, transportv1.Transport_TRANSPORT_RPC, transportv1.Transport_TRANSPORT_WS}},
			want:   []transportv1.Transport{transportv1.Transport_TRANSPORT_RPC, transportv1.Transport_TRANSPORT_WS},
		},
		{
			name:    "method annotation names no road",
			method:  &transportv1.TransportOptions{Group: "g"},
			wantErr: "names no transport",
		},
		{
			name:    "unspecified is not a road",
			method:  &transportv1.TransportOptions{On: []transportv1.Transport{transportv1.Transport_TRANSPORT_UNSPECIFIED}},
			wantErr: "TRANSPORT_UNSPECIFIED",
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			on, group, err := resolve(tc.svc, tc.method)
			if tc.wantErr != "" {
				if err == nil || !strings.Contains(err.Error(), tc.wantErr) {
					t.Fatalf("got %v, want an error containing %q", err, tc.wantErr)
				}
				return
			}
			if err != nil {
				t.Fatal(err)
			}
			if !slices.Equal(on, tc.want) {
				t.Errorf("roads: got %v, want %v", on, tc.want)
			}
			if group != tc.wantGroup {
				t.Errorf("group: got %q, want %q", group, tc.wantGroup)
			}
		})
	}
}

// TestStreamingRefused: interchange is unary only, so the plugin refuses
// rather than emitting a service whose contract it cannot keep.
func TestStreamingRefused(t *testing.T) {
	file := &descriptorpb.FileDescriptorProto{
		Name:    proto.String("stream/v1/stream.proto"),
		Package: proto.String("stream.v1"),
		Syntax:  proto.String("proto3"),
		Options: &descriptorpb.FileOptions{GoPackage: proto.String("example.com/gen/stream/v1;streamv1")},
		MessageType: []*descriptorpb.DescriptorProto{
			{Name: proto.String("Tick")},
		},
		Service: []*descriptorpb.ServiceDescriptorProto{{
			Name: proto.String("Feed"),
			Method: []*descriptorpb.MethodDescriptorProto{{
				Name:            proto.String("Watch"),
				InputType:       proto.String(".stream.v1.Tick"),
				OutputType:      proto.String(".stream.v1.Tick"),
				ServerStreaming: proto.Bool(true),
			}},
		}},
	}
	// A real protoc request carries SourceCodeInfo, so the refusal can point
	// at the line. Descriptors rebuilt from generated Go carry none, which is
	// why this case is synthesised rather than read off the fixture.
	file.SourceCodeInfo = &descriptorpb.SourceCodeInfo{
		Location: []*descriptorpb.SourceCodeInfo_Location{{
			Path: []int32{6, 0, 2, 0}, // service 0, method 0
			Span: []int32{11, 2, 40},
		}},
	}
	req := &pluginpb.CodeGeneratorRequest{
		FileToGenerate: []string{file.GetName()},
		Parameter:      proto.String("paths=source_relative"),
		ProtoFile:      []*descriptorpb.FileDescriptorProto{file},
	}
	_, err := plugintest.Run(req, protogen.Options{}, generate)
	if err == nil {
		t.Fatal("generated code for a streaming RPC; want a refusal")
	}
	if !strings.Contains(err.Error(), "stream.v1.Feed.Watch") || !strings.Contains(err.Error(), "stream/v1/stream.proto:12:3") {
		t.Errorf("error must name the RPC and the line to edit, got: %v", err)
	}
}

// TestDocComments covers what the golden cannot: the fixture's descriptors
// come from generated Go and carry no comments, so without this the comment
// path would only ever run under a real buf invocation.
func TestDocComments(t *testing.T) {
	file := &descriptorpb.FileDescriptorProto{
		Name:        proto.String("doc/v1/doc.proto"),
		Package:     proto.String("doc.v1"),
		Syntax:      proto.String("proto3"),
		Options:     &descriptorpb.FileOptions{GoPackage: proto.String("example.com/gen/doc/v1;docv1")},
		MessageType: []*descriptorpb.DescriptorProto{{Name: proto.String("Thing")}},
		Service: []*descriptorpb.ServiceDescriptorProto{{
			Name: proto.String("DocService"),
			Method: []*descriptorpb.MethodDescriptorProto{{
				Name:       proto.String("Do"),
				InputType:  proto.String(".doc.v1.Thing"),
				OutputType: proto.String(".doc.v1.Thing"),
			}},
		}},
		SourceCodeInfo: &descriptorpb.SourceCodeInfo{
			Location: []*descriptorpb.SourceCodeInfo_Location{{
				Path:            []int32{6, 0, 2, 0},
				Span:            []int32{11, 2, 40},
				LeadingComments: proto.String(" Do the thing.\n Twice.\n"),
			}},
		},
	}
	files, err := plugintest.Run(&pluginpb.CodeGeneratorRequest{
		FileToGenerate: []string{file.GetName()},
		Parameter:      proto.String("paths=source_relative"),
		ProtoFile:      []*descriptorpb.FileDescriptorProto{file},
	}, protogen.Options{}, generate)
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	src := files["doc/v1/docv1bus/doc_bus.pb.go"]
	if !strings.Contains(src, "\t// Do the thing.\n\t// Twice.\n\tDo(context.Context") {
		t.Errorf("the RPC's documentation did not reach the server interface:\n%s", src)
	}
}
