package main

import (
	"fmt"
	"slices"

	transportv1 "github.com/darmawan01/interchange/gen/go/interchange/transport/v1"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
)

// defaultRoads is what an RPC with no annotation anywhere travels: the two
// synchronous roads. A method reaches a broker only because someone wrote it
// down.
var defaultRoads = []transportv1.Transport{
	transportv1.Transport_TRANSPORT_RPC,
	transportv1.Transport_TRANSPORT_REST,
}

// busRoads are the roads served by the message engine rather than by HTTP.
var busRoads = []transportv1.Transport{
	transportv1.Transport_TRANSPORT_BUS,
	transportv1.Transport_TRANSPORT_MQTT,
	transportv1.Transport_TRANSPORT_WS,
}

// resolve implements the rule stated in transports.proto: a per-method
// (transports) annotation replaces the service-level default entirely -- it
// is not merged with it, so a reviewer reads exactly one annotation to know
// where an RPC goes. Group follows the same replacement.
//
// An annotation that is present but names no road is an error rather than a
// silent fall-through to the default: the two readings of `(transports) = {
// group: "x" }` are "only change the group" and "expose on nothing", and
// guessing between them is how an internal RPC ends up on a public bus.
func resolve(svcOpt *transportv1.ServiceTransportOptions, mOpt *transportv1.TransportOptions) ([]transportv1.Transport, string, error) {
	switch {
	case mOpt != nil:
		on, err := normalize(mOpt.GetOn())
		if err != nil {
			return nil, "", fmt.Errorf("(transports): %w", err)
		}
		return on, mOpt.GetGroup(), nil
	case svcOpt != nil:
		on, err := normalize(svcOpt.GetOn())
		if err != nil {
			return nil, "", fmt.Errorf("(service_transports): %w", err)
		}
		return on, svcOpt.GetGroup(), nil
	default:
		return slices.Clone(defaultRoads), "", nil
	}
}

// normalize sorts and dedupes the road list. It is a set: emitting it in
// annotation order would make the generated bytes depend on the order someone
// happened to type, and the drift gate would flap on a cosmetic edit.
func normalize(on []transportv1.Transport) ([]transportv1.Transport, error) {
	if len(on) == 0 {
		return nil, fmt.Errorf("annotation names no transport; remove it to accept the default, or list the roads explicitly")
	}
	out := slices.Clone(on)
	slices.Sort(out)
	out = slices.Compact(out)
	for _, t := range out {
		if t == transportv1.Transport_TRANSPORT_UNSPECIFIED {
			return nil, fmt.Errorf("TRANSPORT_UNSPECIFIED is not a road")
		}
	}
	return out, nil
}

// onBus reports whether any of the roads is served by the message engine,
// which is what decides whether a service gets a generated bus client.
func onBus(on []transportv1.Transport) bool {
	for _, t := range on {
		if slices.Contains(busRoads, t) {
			return true
		}
	}
	return false
}

func serviceTransportOptions(opts *descriptorpb.ServiceOptions) *transportv1.ServiceTransportOptions {
	if opts == nil || !proto.HasExtension(opts, transportv1.E_ServiceTransports) {
		return nil
	}
	o, _ := proto.GetExtension(opts, transportv1.E_ServiceTransports).(*transportv1.ServiceTransportOptions)
	return o
}

func methodTransportOptions(opts *descriptorpb.MethodOptions) *transportv1.TransportOptions {
	if opts == nil || !proto.HasExtension(opts, transportv1.E_Transports) {
		return nil
	}
	o, _ := proto.GetExtension(opts, transportv1.E_Transports).(*transportv1.TransportOptions)
	return o
}

func methodInternal(opts *descriptorpb.MethodOptions) bool {
	if opts == nil || !proto.HasExtension(opts, transportv1.E_Internal) {
		return false
	}
	b, _ := proto.GetExtension(opts, transportv1.E_Internal).(bool)
	return b
}

// idempotent reports idempotency_level = NO_SIDE_EFFECTS, which is what lets
// the Connect binding answer a cacheable GET.
func idempotent(opts *descriptorpb.MethodOptions) bool {
	return opts.GetIdempotencyLevel() == descriptorpb.MethodOptions_NO_SIDE_EFFECTS
}
