package main

import (
	"fmt"
	"path"
	"strings"

	"github.com/darmawan01/interchange/tools/internal/genutil"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

func emit(p *protogen.Plugin, f *protogen.File, svcs []service) {
	pkg := string(f.GoPackageName) + "cli"
	dir := path.Dir(f.GeneratedFilenamePrefix)
	name := path.Join(dir, pkg, path.Base(f.GeneratedFilenamePrefix)+"_cli.pb.go")
	importPath := protogen.GoImportPath(path.Join(string(f.GoImportPath), pkg))

	im := genutil.NewImporter(p)
	var b strings.Builder
	for _, s := range svcs {
		emitCoverage(&b, im, s)
		emitCommands(&b, im, s)
	}

	g := p.NewGeneratedFile(name, importPath)
	g.P("// Code generated by protoc-gen-cli. DO NOT EDIT.")
	g.P("// source: ", f.Desc.Path())
	g.P()
	g.P("package ", pkg)
	g.P()
	im.Write(g)
	g.P(b.String())
}

func emitCoverage(b *strings.Builder, im *genutil.Importer, s service) {
	pf := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	sup := im.Pkg(clisupportPkg)

	pf("// %sCoverage reports which RPCs the command tree below actually", s.goName)
	pf("// fronts. A CLI that silently covers most of a service is worse than no")
	pf("// CLI: the gap is invisible until someone needs the missing call. Print")
	pf("// it, or build with require_annotation=true to make a gap fail the build.")
	pf("func %sCoverage() %s.Coverage {", s.goName, sup)
	pf("\treturn %s.Coverage{", sup)
	pf("\t\tService: %q,", s.fullName)
	emitStrings(b, "Covered", s.covered)
	emitStrings(b, "Skipped", s.skipped)
	emitStrings(b, "Missing", s.missing)
	pf("\t}")
	pf("}")
	pf("")
}

func emitStrings(b *strings.Builder, field string, values []string) {
	pf := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	if len(values) == 0 {
		pf("\t\t%s: nil,", field)
		return
	}
	pf("\t\t%s: []string{", field)
	for _, v := range values {
		pf("\t\t\t%q,", v)
	}
	pf("\t\t},")
}

func emitCommands(b *strings.Builder, im *genutil.Importer, s service) {
	pf := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	cobra := im.Pkg(cobraPkg)
	sup := im.Pkg(clisupportPkg)

	pf("// Register%sCommands mounts %s under root. Commands call", s.goName, s.name)
	pf("// through inv, so the same tree runs over Connect, over a bus, or against")
	pf("// a stub: a CLI is a caller, and a caller does not pick the road.")
	if len(s.commands) == 0 {
		pf("//")
		pf("// No RPC on this service is annotated, so this mounts nothing. See")
		pf("// %sCoverage.", s.goName)
	}
	pf("func Register%sCommands(root *%s.Command, inv %s.Invoker) {", s.goName, cobra, sup)
	for _, c := range s.commands {
		emitCommand(b, im, c)
	}
	pf("}")
	pf("")
}

func emitCommand(b *strings.Builder, im *genutil.Importer, c command) {
	pf := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	cobra := im.Pkg(cobraPkg)
	sup := im.Pkg(clisupportPkg)
	leaf := c.pathSpec[len(c.pathSpec)-1]

	use := leaf
	for _, a := range c.args {
		use += " <" + kebab(a) + ">"
	}

	pf("\t{")
	pf("\t\tvar (")
	for _, fl := range c.flags {
		pf("\t\t\t%s %s", fl.varName, goType(fl.kind))
	}
	pf("\t\t\tflagRequestJSON string")
	pf("\t\t)")
	pf("\t\tcmd := &%s.Command{", cobra)
	pf("\t\t\tUse:   %q,", use)
	if c.short != "" {
		pf("\t\t\tShort: %q,", c.short)
	}
	if c.long != "" {
		pf("\t\t\tLong:  %q,", c.long)
	}
	if len(c.args) == 0 {
		pf("\t\t\tArgs:  %s.NoArgs,", cobra)
	} else {
		pf("\t\t\tArgs:  %s.ExactArgs(%d),", cobra, len(c.args))
	}
	pf("\t\t\tRunE: func(cmd *%s.Command, args []string) error {", cobra)
	pf("\t\t\t\treq := &%s{}", im.Ref(c.input))
	pf("\t\t\t\tif err := %s.ApplyRequestJSON(req, flagRequestJSON); err != nil {", sup)
	pf("\t\t\t\t\treturn err")
	pf("\t\t\t\t}")
	for i, a := range c.args {
		pf("\t\t\t\tif err := %s.SetField(req, %q, args[%d]); err != nil {", sup, a, i)
		pf("\t\t\t\t\treturn err")
		pf("\t\t\t\t}")
	}
	for _, fl := range c.flags {
		// Only a flag the user actually typed touches the request: otherwise
		// a zero-valued flag would overwrite a field set by --request-json.
		pf("\t\t\t\tif cmd.Flags().Changed(%q) {", fl.flagName)
		emitApply(b, sup, fl)
		pf("\t\t\t\t}")
	}
	pf("\t\t\t\tresp := &%s{}", im.Ref(c.output))
	pf("\t\t\t\tif err := inv.Invoke(cmd.Context(), %q, req, resp); err != nil {", c.procedure)
	pf("\t\t\t\t\treturn err")
	pf("\t\t\t\t}")
	pf("\t\t\t\treturn %s.PrintJSON(cmd.OutOrStdout(), resp)", sup)
	pf("\t\t\t},")
	pf("\t\t}")
	for _, fl := range c.flags {
		pf("\t\tcmd.Flags().%s(&%s, %q, %s, %q)", flagFunc(fl.kind), fl.varName, fl.flagName, zeroLiteral(fl.kind), fl.protoName+" ("+kindName(fl.kind)+")")
	}
	pf("\t\tcmd.Flags().StringVar(&flagRequestJSON, %q, \"\", %q)", requestJSONFlag,
		"the whole request as JSON; fields no flag can carry go here, and flags override it")
	if len(c.pathSpec) == 1 {
		pf("\t\troot.AddCommand(cmd)")
	} else {
		pf("\t\t%s.EnsurePath(root, %s).AddCommand(cmd)", sup, quoteList(c.pathSpec[:len(c.pathSpec)-1]))
	}
	pf("\t}")
}

func emitApply(b *strings.Builder, sup string, fl flag) {
	pf := func(format string, args ...any) { fmt.Fprintf(b, format+"\n", args...) }
	switch {
	case fl.kind == protoreflect.EnumKind:
		// The parse is shared: an enum flag accepts a value name or a number,
		// and one error message says which values exist.
		pf("\t\t\t\t\tif err := %s.SetField(req, %q, %s); err != nil {", sup, fl.protoName, fl.varName)
		pf("\t\t\t\t\t\treturn err")
		pf("\t\t\t\t\t}")
	case fl.kind == protoreflect.BytesKind:
		pf("\t\t\t\t\treq.%s = []byte(%s)", fl.goName, fl.varName)
	case fl.optional:
		pf("\t\t\t\t\tv := %s", fl.varName)
		pf("\t\t\t\t\treq.%s = &v", fl.goName)
	default:
		pf("\t\t\t\t\treq.%s = %s", fl.goName, fl.varName)
	}
}

func goType(k protoreflect.Kind) string {
	switch k {
	case protoreflect.BoolKind:
		return "bool"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return "int32"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return "int64"
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return "uint32"
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "uint64"
	case protoreflect.FloatKind:
		return "float32"
	case protoreflect.DoubleKind:
		return "float64"
	default:
		return "string"
	}
}

func flagFunc(k protoreflect.Kind) string {
	switch goType(k) {
	case "bool":
		return "BoolVar"
	case "int32":
		return "Int32Var"
	case "int64":
		return "Int64Var"
	case "uint32":
		return "Uint32Var"
	case "uint64":
		return "Uint64Var"
	case "float32":
		return "Float32Var"
	case "float64":
		return "Float64Var"
	default:
		return "StringVar"
	}
}

func zeroLiteral(k protoreflect.Kind) string {
	switch goType(k) {
	case "bool":
		return "false"
	case "string":
		return `""`
	default:
		return "0"
	}
}

func kindName(k protoreflect.Kind) string {
	if k == protoreflect.EnumKind {
		return "enum"
	}
	return k.String()
}

func quoteList(values []string) string {
	parts := make([]string, 0, len(values))
	for _, v := range values {
		parts = append(parts, fmt.Sprintf("%q", v))
	}
	return strings.Join(parts, ", ")
}
