// Package gentmpl turns interchange.yaml's generate[] block into a
// buf.gen.yaml template.
//
// interchange.yaml is the single source of truth for which generators run.
// ix synthesizes the buf template from it on every generate, so there is no
// second file to keep in sync -- and `ix verify` checks that the committed
// buf.gen.yaml (which exists so a plain `buf generate` still works) says the
// same thing.
package gentmpl

import (
	"bytes"
	"fmt"
	"path"
	"strings"

	"github.com/darmawan01/interchange/ix/internal/config"
	"gopkg.in/yaml.v3"
)

// Header is the banner on a generated template. It carries no timestamp and
// no version string: same input, same bytes, or the drift gate flaps.
const Header = "# Generated by ix from interchange.yaml -- DO NOT EDIT.\n" +
	"# It exists so `buf generate` works without ix; ix synthesizes its own copy.\n"

type template struct {
	Version string          `yaml:"version"`
	Clean   bool            `yaml:"clean"`
	Inputs  []input         `yaml:"inputs,omitempty"`
	Managed *config.Managed `yaml:"managed,omitempty"`
	Plugins []plugin        `yaml:"plugins"`
}

type input struct {
	Directory string `yaml:"directory"`
}

type plugin struct {
	Remote   string   `yaml:"remote,omitempty"`
	Local    string   `yaml:"local,omitempty"`
	Out      string   `yaml:"out"`
	Opt      []string `yaml:"opt,omitempty"`
	Strategy string   `yaml:"strategy,omitempty"`
}

// Options tunes the synthesized template.
type Options struct {
	// OutPrefix relocates every generator's output under a directory. The
	// drift gate uses it to regenerate into a temp tree without touching the
	// working copy.
	OutPrefix string

	// Only, when non-empty, keeps just the generators whose plugin matches.
	Only []string
}

// Build renders the template for a config.
func Build(c *config.Config, o Options) ([]byte, error) {
	if len(c.Generate) == 0 {
		return nil, fmt.Errorf("%s: generate: no generators configured -- nothing to run", c.Path)
	}
	t := template{Version: "v2", Managed: c.Managed}
	for _, d := range c.ProtoDirs() {
		t.Inputs = append(t.Inputs, input{Directory: d})
	}
	for _, g := range c.Generate {
		if len(o.Only) > 0 && !contains(o.Only, g.Plugin) {
			continue
		}
		p := plugin{Out: relocate(g.Out, o.OutPrefix), Opt: g.Opt, Strategy: g.Strategy}
		if g.Local() {
			p.Local = g.Plugin
		} else {
			p.Remote = g.Plugin
		}
		t.Plugins = append(t.Plugins, p)
	}
	if len(t.Plugins) == 0 {
		return nil, fmt.Errorf("no generator matches %s", strings.Join(o.Only, ", "))
	}

	var buf bytes.Buffer
	buf.WriteString(Header)
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(t); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func relocate(out, prefix string) string {
	if prefix == "" {
		return out
	}
	return path.Join(prefix, out)
}

func contains(ss []string, s string) bool {
	for _, x := range ss {
		if x == s {
			return true
		}
	}
	return false
}
